import os
import json
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Image as RLImage, Table, TableStyle
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle


def build_pdf_report(app, prediction, user):
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("TitleX", parent=styles["Title"], textColor=colors.HexColor("#1c3d5a"))
    h2 = ParagraphStyle("H2", parent=styles["Heading2"], textColor=colors.HexColor("#1c3d5a"))
    normal = styles["Normal"]

    out_path = os.path.join(app.config["REPORT_FOLDER"], f"report_{prediction.id}.pdf")
    doc = SimpleDocTemplate(out_path, pagesize=A4, topMargin=20 * mm, bottomMargin=18 * mm)

    story = []
    story.append(Paragraph("Few-Shot Rare Ophthalmic Disease Detection", title_style))
    story.append(Paragraph("Automated Prediction Report", styles["Heading3"]))
    story.append(Spacer(1, 10))

    meta = [
        ["Report ID", f"RPT-{prediction.id:06d}"],
        ["Generated", prediction.created_at.strftime("%Y-%m-%d %H:%M UTC")],
        ["Clinician / User", f"{user.full_name} ({user.email})"],
        ["Patient / Case Reference", prediction.patient_ref or "N/A"],
        ["Few-Shot Setting", f"{prediction.n_way}-way {prediction.k_shot}-shot"],
    ]
    t = Table(meta, colWidths=[55 * mm, 110 * mm])
    t.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (0, -1), colors.HexColor("#1c3d5a")),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LINEBELOW", (0, 0), (-1, -1), 0.3, colors.lightgrey),
    ]))
    story.append(t)
    story.append(Spacer(1, 14))

    story.append(Paragraph("Prediction Summary", h2))
    pred_table = Table(
        [["Predicted Class", prediction.predicted_class],
         ["Confidence", f"{prediction.confidence*100:.2f}%"]],
        colWidths=[55 * mm, 110 * mm],
    )
    pred_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#eef4fa")),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#c9d8e6")),
    ]))
    story.append(pred_table)
    story.append(Spacer(1, 12))

    probs = json.loads(prediction.class_probs_json)
    sorted_probs = sorted(probs.items(), key=lambda kv: kv[1], reverse=True)
    prob_rows = [["Rare Disease Class", "Similarity Probability"]] + [
        [c, f"{p*100:.2f}%"] for c, p in sorted_probs
    ]
    prob_table = Table(prob_rows, colWidths=[110 * mm, 55 * mm])
    prob_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1c3d5a")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.lightgrey),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f5f8fb")]),
    ]))
    story.append(Paragraph("Class Probabilities (Prototypical Network softmax over distances)", h2))
    story.append(prob_table)
    story.append(Spacer(1, 14))

    # Images
    img_dir = app.config["UPLOAD_FOLDER"]
    heat_dir = app.config["HEATMAP_FOLDER"]
    orig_path = os.path.join(img_dir, prediction.original_image)
    heat_path = os.path.join(heat_dir, prediction.heatmap_image) if prediction.heatmap_image else None

    story.append(Paragraph("Retinal Image & Grad-CAM Explanation", h2))
    img_row = []
    if os.path.exists(orig_path):
        img_row.append(RLImage(orig_path, width=75 * mm, height=75 * mm))
    if heat_path and os.path.exists(heat_path):
        img_row.append(RLImage(heat_path, width=75 * mm, height=75 * mm))
    if img_row:
        img_table = Table([img_row], colWidths=[80 * mm] * len(img_row))
        story.append(img_table)
        cap_row = [["Original Fundus Image", "Grad-CAM Attention Overlay"][:len(img_row)][i] for i in range(len(img_row))]
        story.append(Table([cap_row], colWidths=[80 * mm] * len(img_row)))
    story.append(Spacer(1, 12))

    if prediction.notes:
        story.append(Paragraph("Clinical Notes", h2))
        story.append(Paragraph(prediction.notes, normal))
        story.append(Spacer(1, 12))

    disclaimer = (
        "<b>Disclaimer:</b> This report was generated by an AI research/demonstration "
        "system using a Prototypical (few-shot) Network over a small support set. "
        "It is intended to illustrate an automated rare-disease detection pipeline "
        "and is <b>not</b> a validated diagnostic device. All findings must be reviewed "
        "and confirmed by a qualified ophthalmologist before any clinical decision is made."
    )
    story.append(Paragraph(disclaimer, ParagraphStyle("Disc", parent=normal, fontSize=8, textColor=colors.grey)))

    doc.build(story)
    return out_path